# Generated by Django 5.0.1 on 2024-02-21 10:16

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_plot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="plot_image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[720, 720],
                upload_to="photos/",
            ),
        ),
    ]
