# Generated by Django 5.0.1 on 2024-01-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="fav_campsite",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
