# Generated by Django 5.0.1 on 2024-02-21 10:25

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0002_alter_profile_fav_campsite_alter_profile_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                null=True,
                quality=-1,
                scale=None,
                size=[720, 720],
                upload_to="images/",
            ),
        ),
    ]
