# Generated by Django 5.0.1 on 2024-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0002_alter_profile_fav_campsite_alter_profile_nationality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="campermode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Hammock", "Hammock"),
                    ("Small Tent", "Small Tent"),
                    ("Large Tent", "Large tent"),
                    ("Car", "Car"),
                    ("Van", "Van"),
                    ("CamperVan", "CamperVan"),
                    ("Motorhome", "Motorhome"),
                    ("Small Caravan", "Small Caravan"),
                    ("Large Caravan", "Large Caravan"),
                    ("Trailer Tent", "Trailer Tent"),
                    ("Cabin/Mobile Home", "Cabin/Mobile Home"),
                    ("Under the Stars", "Under the Stars"),
                ],
                default="Hammock",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="nationality",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="realname",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
