# Generated by Django 5.0.1 on 2024-02-23 17:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_users", "0003_alter_profile_campermode_alter_profile_nationality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="realname",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format=None,
                keep_meta=True,
                max_length=40,
                null=True,
                quality=85,
                scale=None,
                size=[600, 600],
                upload_to="",
            ),
        ),
    ]
