# Generated by Django 5.0.1 on 2024-02-08 23:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a_inbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inboxmessage",
            options={"ordering": ["-created"]},
        ),
    ]
