# Generated by Django 5.0.1 on 2024-02-09 19:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a_inbox", "0002_alter_inboxmessage_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
